// Package managementrouter provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.6.0 DO NOT EDIT.
package managementrouter

import (
	"fmt"
	"net/http"

	"github.com/gorilla/mux"
)

// AlertRuleSpec Specification of a Prometheus alerting or recording rule. Maps to prometheus-operator Rule fields.
type AlertRuleSpec struct {
	// Alert Name of the alert. Must be set for alerting rules.
	Alert *string `json:"alert,omitempty"`

	// Annotations Annotations to attach to alerts produced by the rule.
	Annotations *map[string]string `json:"annotations,omitempty"`

	// Expr PromQL expression to evaluate.
	Expr *string `json:"expr,omitempty"`

	// For Duration the condition must be true before firing (e.g. "5m").
	For *string `json:"for,omitempty"`

	// KeepFiringFor Duration to keep alert firing after the condition is no longer true.
	KeepFiringFor *string `json:"keepFiringFor,omitempty"`

	// Labels Labels to attach to alerts produced by the rule.
	Labels *map[string]string `json:"labels,omitempty"`

	// Record Name of the time series for recording rules.
	Record *string `json:"record,omitempty"`
}

// CreateAlertRuleRequest defines model for CreateAlertRuleRequest.
type CreateAlertRuleRequest struct {
	// AlertingRule Specification of a Prometheus alerting or recording rule. Maps to prometheus-operator Rule fields.
	AlertingRule *AlertRuleSpec `json:"alertingRule,omitempty"`

	// PrometheusRule Identifies the PrometheusRule resource and rule group where the alert rule will be stored. Required for user-defined alert rules.
	PrometheusRule *PrometheusRuleTarget `json:"prometheusRule,omitempty"`
}

// CreateAlertRuleResponse defines model for CreateAlertRuleResponse.
type CreateAlertRuleResponse struct {
	// Id Computed stable ID for the created alert rule.
	Id string `json:"id"`
}

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	// Error Human-readable error message.
	Error string `json:"error"`
}

// PrometheusRuleTarget Identifies the PrometheusRule resource and rule group where the alert rule will be stored. Required for user-defined alert rules.
type PrometheusRuleTarget struct {
	// GroupName Name of the rule group within the PrometheusRule. Optional.
	GroupName *string `json:"groupName,omitempty"`

	// PrometheusRuleName Name of the PrometheusRule resource.
	PrometheusRuleName string `json:"prometheusRuleName"`

	// PrometheusRuleNamespace Namespace of the PrometheusRule resource.
	PrometheusRuleNamespace string `json:"prometheusRuleNamespace"`
}

// CreateAlertRuleJSONRequestBody defines body for CreateAlertRule for application/json ContentType.
type CreateAlertRuleJSONRequestBody = CreateAlertRuleRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Create an alert rule
	// (POST /rules)
	CreateAlertRule(w http.ResponseWriter, r *http.Request)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// CreateAlertRule operation middleware
func (siw *ServerInterfaceWrapper) CreateAlertRule(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateAlertRule(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, GorillaServerOptions{})
}

type GorillaServerOptions struct {
	BaseURL          string
	BaseRouter       *mux.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r *mux.Router) http.Handler {
	return HandlerWithOptions(si, GorillaServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r *mux.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, GorillaServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options GorillaServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = mux.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.HandleFunc(options.BaseURL+"/rules", wrapper.CreateAlertRule).Methods("POST")

	return r
}
