FROM registry.redhat.io/ubi9/nodejs-22:9.6-1755075210 AS web-builder

USER 0

WORKDIR /usr/src/app

COPY web/package*.json web/
COPY Makefile Makefile

RUN make install-frontend-ci

COPY web/. web/.
COPY scripts/. scripts/.

ENTRYPOINT ["make", "lint-frontend"]
