FROM registry.redhat.io/ubi9/nodejs-22:9.6-1755075210 AS web-builder

WORKDIR /opt/app-root

USER 0

ENV HUSKY=0

COPY web/package.json web/package-lock.json web/
COPY Makefile Makefile
RUN make install-frontend-ci

COPY web/ web/
RUN make build-frontend

# Almost all images from Red Hat are still on go1.21, however I found one that the cne team has
# created. Once official Red Hat images are available for local development and pulling this
# should be updated
FROM brew.registry.redhat.io/rh-osbs/openshift-golang-builder:rhel_9_golang_1.24 as go-builder

WORKDIR /opt/app-root

COPY Makefile Makefile
COPY backend/Makefile backend/Makefile
COPY backend/go.mod backend/go.mod
COPY backend/go.sum backend/go.sum

RUN make install-backend

COPY backend/ backend/

RUN make build-backend

FROM registry.access.redhat.com/ubi9/ubi-minimal

USER 1001

COPY --from=web-builder /opt/app-root/web/dist /opt/app-root/web/dist
COPY --from=go-builder /opt/app-root/plugin-backend /opt/app-root
COPY config/ /opt/app-root/config

ENTRYPOINT ["/opt/app-root/plugin-backend", "-static-path", "/opt/app-root/web/dist", "-config-path", "/opt/app-root/config"]
