FROM cypress/included:12.17.4

WORKDIR /usr/src/app

ENV HUSKY=0

COPY web/package.json web/package-lock.json ./

RUN npm ci

COPY web/console-extensions.json web/cypress.config.ts web/tsconfig.json web/webpack.config.ts ./
COPY web/cypress/ ./cypress
COPY web/locales/ ./locales
COPY web/src/ ./src
RUN npm run build

ENTRYPOINT ["npm", "run", "cypress:run:ci"]
