FROM registry.redhat.io/ubi9/nodejs-22:9.6-1755075210 AS web-builder

USER 0

WORKDIR /usr/src/app

COPY web/package*.json web/
COPY web/patches/@openshift-console+dynamic-plugin-sdk+4.22.0-prerelease.2.patch  web/patches/
COPY Makefile Makefile

RUN make install-frontend-ci
RUN make patch-frontend

COPY web/. web/.
COPY scripts/. scripts/.

ENTRYPOINT ["make", "lint-frontend"]
