FROM registry.redhat.io/ubi9/nodejs-22:9.6-1755075210 AS web-builder

USER 0

WORKDIR /usr/src/app

COPY web/package*.json web/
COPY Makefile Makefile

RUN make install-frontend-ci

COPY web/. web/.
COPY scripts/. scripts/.

RUN chown -R 1001:0 /usr/src/app /opt/app-root/src/.npm && \
    chmod -R g=u /usr/src/app /opt/app-root/src/.npm

USER 1001

ENTRYPOINT ["make", "lint-frontend"]
