#!/usr/bin/env bash

# Interactive configurator for Cypress environment variables.
#
# Flow: Cluster Connection → Installation Mode → (conditional) Operators → Runtime
# Options are gated so irrelevant questions are never shown.
#
# How to use:
# 1) Source into current shell:    source ./configure-env.sh
# 2) Generate an exports file:     ./configure-env.sh && source ./export-env.sh
# 3) Show current configuration:   source ./configure-env.sh --show

# When sourced from zsh, delegate to bash for the interactive prompts
# (zsh doesn't support bash's `read -p`), then auto-source the result.
if [[ -n "${ZSH_VERSION:-}" ]]; then
  _cfg_dir="$(cd "$(dirname "$0")" && pwd)"
  _cfg_out="$_cfg_dir/export-env.sh"
  _CONFIGURE_ENV_AUTO_SOURCE=1 bash "$_cfg_dir/configure-env.sh" "$@"
  _cfg_rc=$?
  if [[ $_cfg_rc -eq 0 && -f "$_cfg_out" && "$*" != *--show* && "$*" != *-s* ]]; then
    source "$_cfg_out"
    echo "Exported variables into current shell."
  fi
  unset _cfg_dir _cfg_out _cfg_rc
  return 0 2>/dev/null || exit 0
fi

is_sourced() {
  [[ "${BASH_SOURCE[0]}" != "$0" ]]
}

if ! is_sourced; then
  set -euo pipefail
fi

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
OUTPUT_FILE_DEFAULT="$SCRIPT_DIR/export-env.sh"

print_header() {
  echo ""
  echo "========================================"
  echo "Cypress environment setup"
  echo "========================================"
  echo "Values in brackets are defaults (press Enter to accept)."
  echo ""
}

print_usage() {
  cat <<'EOF'
Usage: configure-env.sh [--show] [--help]

Options:
  --show, -s   Show current values of Cypress environment variables and exit
  --help, -h   Show this help and exit

Run without flags to be interactively prompted and either export to current
shell (if sourced) or write an export file.
EOF
}

section_header() {
  echo ""
  echo "--- $1 ---"
  echo ""
}

ask() {
  local prompt=$1
  local default_value=${2-}
  local input
  if [[ -n "$default_value" ]]; then
    read -r -p "$prompt [$default_value]: " input || true
    echo "${input:-$default_value}"
  else
    read -r -p "$prompt: " input || true
    echo "$input"
  fi
}

ask_required() {
  local prompt=$1
  local default_value=${2-}
  local value
  while true; do
    value=$(ask "$prompt" "$default_value")
    if [[ -n "$value" ]]; then
      echo "$value"
      return 0
    fi
    echo "Value is required. Please enter a value." 1>&2
  done
}

ask_yes_no() {
  local prompt=$1
  local default_answer=${2:-n}
  local suffix="[y/N]"
  [[ "$default_answer" =~ ^[Yy]$ ]] && suffix="[Y/n]"
  local yn
  while true; do
    read -r -p "$prompt $suffix: " yn || true
    yn=${yn:-$default_answer}
    case "$yn" in
      [Yy]|[Yy][Ee][Ss]) echo "y"; return 0;;
      [Nn]|[Nn][Oo]) echo "n"; return 0;;
      "") [[ "$default_answer" =~ ^[Yy]$ ]] && echo "y" || echo "n"; return 0;;
    esac
    echo "Please answer y or n." 1>&2
  done
}

bool_to_default_yn() {
  local v=${1-}
  v=$(echo "$v" | tr '[:upper:]' '[:lower:]')
  case "$v" in
    true|1|yes|y) echo "y" ;;
    *) echo "n" ;;
  esac
}

escape_for_single_quotes() {
  # shellcheck disable=SC2001
  sed "s/'/'\\''/g"
}

write_exports_file() {
  local file_path=$1
  shift
  local -a lines=("$@")
  {
    echo "# Generated by configure-env.sh on $(date -u '+%Y-%m-%dT%H:%M:%SZ')"
    echo "# shellcheck shell=bash"
    echo "# Source this file to export Cypress variables for this repository"
    echo ""
    for line in "${lines[@]}"; do
      echo "$line"
    done
  } > "$file_path"
  echo "Wrote $file_path"
}

# Interactively pick a kubeconfig from ~/Downloads or manual entry.
# Prints the chosen path to stdout; UI messages go to stderr.
pick_kubeconfig_interactive() {
  if [[ -d "$HOME/Downloads" ]]; then
    local kubeconfig_files=()
    while IFS= read -r file; do
      kubeconfig_files+=("$file")
    done < <(ls -t "$HOME/Downloads"/*kubeconfig* 2>/dev/null | head -10)

    if [[ ${#kubeconfig_files[@]} -gt 0 ]]; then
      echo "" >&2
      echo "Available kubeconfig files in Downloads:" >&2
      local i
      for i in "${!kubeconfig_files[@]}"; do
        local file_size
        file_size=$(du -h "${kubeconfig_files[$i]}" 2>/dev/null | cut -f1)
        echo "  $((i+1))) ${kubeconfig_files[$i]##*/} (${file_size:-unknown size})" >&2
      done
      echo "  $(( ${#kubeconfig_files[@]} + 1 ))) Enter custom path" >&2

      local choice
      while true; do
        choice=$(ask "Choose kubeconfig (1-$(( ${#kubeconfig_files[@]} + 1 )))" "")
        if [[ "$choice" =~ ^[0-9]+$ ]] && [[ "$choice" -ge 1 ]] && [[ "$choice" -le $(( ${#kubeconfig_files[@]} + 1 )) ]]; then
          break
        fi
        echo "Please enter a number between 1 and $(( ${#kubeconfig_files[@]} + 1 ))." >&2
      done

      if [[ "$choice" -le ${#kubeconfig_files[@]} ]]; then
        echo "${kubeconfig_files[$((choice-1))]}"
        return 0
      fi
    fi
  fi

  ask_required "Path to kubeconfig" ""
}

print_current_config() {
  echo ""
  echo "Current Cypress configuration:"

  local print_var
  print_var() {
    local name=$1
    local value=${2-}
    if [[ -z "${value:-}" ]]; then
      echo "  $name: [unset]"
    else
      echo "  $name: $value"
    fi
  }

  local v

  echo ""
  echo "  -- Cluster Connection --"
  v=${CYPRESS_KUBECONFIG_PATH-}
  if [[ -n "${v:-}" && ! -f "$v" ]]; then
    v+=" (file not found)"
  fi
  print_var "CYPRESS_KUBECONFIG_PATH" "$v"
  print_var "CYPRESS_BASE_URL" "${CYPRESS_BASE_URL-}"
  print_var "CYPRESS_LOGIN_IDP" "${CYPRESS_LOGIN_IDP-}"
  v=${CYPRESS_LOGIN_USERS-}
  if [[ -n "${v:-}" && "$v" == *:* ]]; then
    v="${v%%:*}:********"
  fi
  print_var "CYPRESS_LOGIN_USERS" "$v"

  echo ""
  echo "  -- Installation Mode --"
  print_var "CYPRESS_SKIP_ALL_INSTALL" "${CYPRESS_SKIP_ALL_INSTALL-}"

  echo ""
  echo "  -- COO --"
  print_var "CYPRESS_SKIP_COO_INSTALL" "${CYPRESS_SKIP_COO_INSTALL-}"
  print_var "CYPRESS_COO_NAMESPACE" "${CYPRESS_COO_NAMESPACE-}"
  print_var "CYPRESS_COO_UI_INSTALL" "${CYPRESS_COO_UI_INSTALL-}"
  print_var "CYPRESS_KONFLUX_COO_BUNDLE_IMAGE" "${CYPRESS_KONFLUX_COO_BUNDLE_IMAGE-}"
  print_var "CYPRESS_CUSTOM_COO_BUNDLE_IMAGE" "${CYPRESS_CUSTOM_COO_BUNDLE_IMAGE-}"
  print_var "CYPRESS_MP_IMAGE" "${CYPRESS_MP_IMAGE-}"
  print_var "CYPRESS_MCP_CONSOLE_IMAGE" "${CYPRESS_MCP_CONSOLE_IMAGE-}"
  print_var "CYPRESS_CHA_IMAGE" "${CYPRESS_CHA_IMAGE-}"

  echo ""
  echo "  -- KBV --"
  print_var "CYPRESS_SKIP_KBV_INSTALL" "${CYPRESS_SKIP_KBV_INSTALL-}"
  print_var "CYPRESS_KBV_UI_INSTALL" "${CYPRESS_KBV_UI_INSTALL-}"
  print_var "CYPRESS_KONFLUX_KBV_BUNDLE_IMAGE" "${CYPRESS_KONFLUX_KBV_BUNDLE_IMAGE-}"
  print_var "CYPRESS_CUSTOM_KBV_BUNDLE_IMAGE" "${CYPRESS_CUSTOM_KBV_BUNDLE_IMAGE-}"
  print_var "CYPRESS_FBC_STAGE_KBV_IMAGE" "${CYPRESS_FBC_STAGE_KBV_IMAGE-}"

  echo ""
  echo "  -- Runtime --"
  print_var "CYPRESS_TIMEZONE" "${CYPRESS_TIMEZONE-}"
  print_var "CYPRESS_MOCK_NEW_METRICS" "${CYPRESS_MOCK_NEW_METRICS-}"
  print_var "CYPRESS_SESSION" "${CYPRESS_SESSION-}"
  print_var "CYPRESS_DEBUG" "${CYPRESS_DEBUG-}"
}

main() {
  local mode_show=false
  while [[ $# -gt 0 ]]; do
    case "$1" in
      --show|-s) mode_show=true; shift;;
      --help|-h) print_usage; return 0;;
      *) echo "Unknown option: $1" 1>&2; print_usage; return 1;;
    esac
  done

  if $mode_show; then
    print_current_config
    return 0
  fi
  print_header

  # ── Initialise all variables from current environment ──────────────
  local base_url="${CYPRESS_BASE_URL-}"
  local login_idp="${CYPRESS_LOGIN_IDP-}"
  local login_users="${CYPRESS_LOGIN_USERS-}"
  local kubeconfig=""
  local mp_image="${CYPRESS_MP_IMAGE-}"
  local coo_namespace="${CYPRESS_COO_NAMESPACE:-openshift-cluster-observability-operator}"
  local skip_coo_install="${CYPRESS_SKIP_COO_INSTALL:-false}"
  local coo_ui_install="${CYPRESS_COO_UI_INSTALL:-false}"
  local konflux_bundle="${CYPRESS_KONFLUX_COO_BUNDLE_IMAGE-}"
  local custom_coo_bundle="${CYPRESS_CUSTOM_COO_BUNDLE_IMAGE-}"
  local mcp_console_image="${CYPRESS_MCP_CONSOLE_IMAGE-}"
  local cha_image="${CYPRESS_CHA_IMAGE-}"
  local timezone="${CYPRESS_TIMEZONE:-UTC}"
  local mock_new_metrics="${CYPRESS_MOCK_NEW_METRICS:-false}"
  local session="${CYPRESS_SESSION:-false}"
  local debug="${CYPRESS_DEBUG:-false}"
  local skip_all_install="${CYPRESS_SKIP_ALL_INSTALL:-false}"
  local skip_kbv_install="${CYPRESS_SKIP_KBV_INSTALL:-false}"
  local kbv_ui_install="${CYPRESS_KBV_UI_INSTALL:-false}"
  local konflux_kbv_bundle="${CYPRESS_KONFLUX_KBV_BUNDLE_IMAGE-}"
  local custom_kbv_bundle="${CYPRESS_CUSTOM_KBV_BUNDLE_IMAGE-}"
  local fbc_stage_kbv_image="${CYPRESS_FBC_STAGE_KBV_IMAGE-}"

  # ── Section 1: Cluster Connection ─────────────────────────────────
  section_header "Cluster Connection"

  # Kubeconfig — default chain: CYPRESS_KUBECONFIG_PATH → KUBECONFIG → ~/.kube/config
  local kube_default="${CYPRESS_KUBECONFIG_PATH:-${KUBECONFIG:-}}"
  if [[ -z "$kube_default" && -f "$HOME/.kube/config" ]]; then kube_default="$HOME/.kube/config"; fi

  if [[ -n "$kube_default" ]]; then
    echo "Kubeconfig: $kube_default"
    local change_kube
    change_kube=$(ask_yes_no "Change kubeconfig?" "n")
    if [[ "$change_kube" == "n" ]]; then
      kubeconfig="$kube_default"
    else
      kubeconfig=$(pick_kubeconfig_interactive)
    fi
  else
    kubeconfig=$(pick_kubeconfig_interactive)
  fi

  if [[ ! -f "$kubeconfig" ]]; then
    echo "Warning: file does not exist at $kubeconfig" 1>&2
  fi

  # Console base URL
  while true; do
    base_url=$(ask_required "Console base URL (e.g. https://console-openshift-console.apps.<cluster>)" "$base_url")
    if [[ "$base_url" =~ ^https?:// ]]; then
      break
    fi
    echo "Must start with http:// or https://" 1>&2
  done

  # Login
  echo ""
  echo "Login method"
  echo "  1) kubeadmin (kube:admin)"
  echo "  2) Custom identity provider"
  local login_choice_default=""
  if [[ "$login_idp" == "kube:admin" ]]; then
    login_choice_default="1"
  elif [[ -n "$login_idp" ]]; then
    login_choice_default="2"
  fi
  local login_choice
  while true; do
    login_choice=$(ask "Choose 1 or 2" "$login_choice_default")
    case "$login_choice" in
      1|2) break;;
      *) echo "Please enter 1 or 2." 1>&2;;
    esac
  done

  local login_user login_pass
  if [[ "$login_choice" == "1" ]]; then
    login_idp="kube:admin"
    login_user="kubeadmin"
    login_pass=$(ask_required "kubeadmin password" "${login_users##*:}")
  else
    login_idp=$(ask_required "Identity provider name" "${login_idp:-flexy-htpasswd-provider}")
    login_user=$(ask_required "Username" "${login_users%%:*}")
    login_pass=$(ask_required "Password" "${login_users##*:}")
  fi
  login_users="$login_user:$login_pass"

  # ── Section 2: Installation Mode ──────────────────────────────────
  section_header "Installation Mode"

  local skip_all_ans
  skip_all_ans=$(ask_yes_no "Skip ALL operator install/cleanup? (for pre-provisioned environments)" "$(bool_to_default_yn "$skip_all_install")")
  skip_all_install="false"
  if [[ "$skip_all_ans" == "y" ]]; then skip_all_install="true"; fi

  if [[ "$skip_all_install" == "false" ]]; then

    # ── Section 3a: COO Installation ────────────────────────────────
    section_header "COO (Cluster Observability Operator)"

    local skip_coo_ans
    skip_coo_ans=$(ask_yes_no "Skip COO installation?" "$(bool_to_default_yn "$skip_coo_install")")
    skip_coo_install="false"
    if [[ "$skip_coo_ans" == "y" ]]; then skip_coo_install="true"; fi

    if [[ "$skip_coo_install" == "false" ]]; then
      coo_namespace=$(ask "COO namespace" "$coo_namespace")

      local coo_ui_ans
      coo_ui_ans=$(ask_yes_no "Install COO from redhat-operators catalog?" "$(bool_to_default_yn "$coo_ui_install")")
      coo_ui_install="false"
      if [[ "$coo_ui_ans" == "y" ]]; then coo_ui_install="true"; fi

      if [[ "$coo_ui_install" == "false" ]]; then
        konflux_bundle=$(ask "Konflux COO bundle image" "$konflux_bundle")
        custom_coo_bundle=$(ask "Custom COO bundle image" "$custom_coo_bundle")
      fi

      mp_image=$(ask "Monitoring Plugin image (CYPRESS_MP_IMAGE)" "$mp_image")
      mcp_console_image=$(ask "Monitoring Console Plugin image (CYPRESS_MCP_CONSOLE_IMAGE)" "$mcp_console_image")
      cha_image=$(ask "Cluster Health Analyzer image (CYPRESS_CHA_IMAGE)" "$cha_image")
    fi

    # ── Section 3b: KBV Installation ────────────────────────────────
    section_header "KBV (OpenShift Virtualization)"

    local skip_kbv_ans
    skip_kbv_ans=$(ask_yes_no "Skip OpenShift Virtualization installation?" "$(bool_to_default_yn "$skip_kbv_install")")
    skip_kbv_install="false"
    if [[ "$skip_kbv_ans" == "y" ]]; then skip_kbv_install="true"; fi

    if [[ "$skip_kbv_install" == "false" ]]; then
      local kbv_ui_ans
      kbv_ui_ans=$(ask_yes_no "Install KBV from redhat-operators catalog?" "$(bool_to_default_yn "$kbv_ui_install")")
      kbv_ui_install="false"
      if [[ "$kbv_ui_ans" == "y" ]]; then kbv_ui_install="true"; fi

      if [[ "$kbv_ui_install" == "false" ]]; then
        konflux_kbv_bundle=$(ask "Konflux KBV bundle image" "$konflux_kbv_bundle")
        custom_kbv_bundle=$(ask "Custom KBV bundle image" "$custom_kbv_bundle")
        fbc_stage_kbv_image=$(ask "KBV FBC image" "$fbc_stage_kbv_image")
      fi
    fi
  fi

  # ── Section 4: Runtime Settings ───────────────────────────────────
  section_header "Runtime Settings"

  timezone=$(ask "Cluster timezone" "$timezone")

  local mock_ans
  mock_ans=$(ask_yes_no "Transform old metric names to new format in mocks?" "$(bool_to_default_yn "$mock_new_metrics")")
  mock_new_metrics="false"
  if [[ "$mock_ans" == "y" ]]; then mock_new_metrics="true"; fi

  local session_ans
  session_ans=$(ask_yes_no "Enable session management for faster test execution?" "$(bool_to_default_yn "$session")")
  session="false"
  if [[ "$session_ans" == "y" ]]; then session="true"; fi

  local debug_ans
  debug_ans=$(ask_yes_no "Enable debug mode?" "$(bool_to_default_yn "$debug")")
  debug="false"
  if [[ "$debug_ans" == "y" ]]; then debug="true"; fi

  # ── Build export lines ────────────────────────────────────────────
  local -a export_lines

  add_export() {
    export_lines+=("export $1='$(printf %s "$2" | escape_for_single_quotes)'")
  }
  add_export_if_set() {
    if [[ -n "$2" ]]; then add_export "$1" "$2"; fi
  }

  add_export      CYPRESS_BASE_URL              "$base_url"
  add_export      CYPRESS_LOGIN_IDP             "$login_idp"
  add_export      CYPRESS_LOGIN_USERS           "$login_users"
  add_export      CYPRESS_KUBECONFIG_PATH       "$kubeconfig"
  add_export      CYPRESS_SKIP_ALL_INSTALL      "$skip_all_install"
  add_export      CYPRESS_SKIP_COO_INSTALL      "$skip_coo_install"
  add_export      CYPRESS_COO_UI_INSTALL        "$coo_ui_install"
  add_export_if_set CYPRESS_COO_NAMESPACE       "$coo_namespace"
  add_export_if_set CYPRESS_MP_IMAGE            "$mp_image"
  add_export_if_set CYPRESS_KONFLUX_COO_BUNDLE_IMAGE "$konflux_bundle"
  add_export_if_set CYPRESS_CUSTOM_COO_BUNDLE_IMAGE  "$custom_coo_bundle"
  add_export_if_set CYPRESS_MCP_CONSOLE_IMAGE   "$mcp_console_image"
  add_export_if_set CYPRESS_CHA_IMAGE           "$cha_image"
  add_export      CYPRESS_SKIP_KBV_INSTALL      "$skip_kbv_install"
  add_export      CYPRESS_KBV_UI_INSTALL        "$kbv_ui_install"
  add_export_if_set CYPRESS_KONFLUX_KBV_BUNDLE_IMAGE "$konflux_kbv_bundle"
  add_export_if_set CYPRESS_CUSTOM_KBV_BUNDLE_IMAGE  "$custom_kbv_bundle"
  add_export_if_set CYPRESS_FBC_STAGE_KBV_IMAGE "$fbc_stage_kbv_image"
  add_export_if_set CYPRESS_TIMEZONE            "$timezone"
  add_export      CYPRESS_MOCK_NEW_METRICS      "$mock_new_metrics"
  add_export      CYPRESS_SESSION               "$session"
  add_export      CYPRESS_DEBUG                 "$debug"

  # ── Output ────────────────────────────────────────────────────────
  echo ""
  if [[ -n "${_CONFIGURE_ENV_AUTO_SOURCE:-}" ]]; then
    write_exports_file "$OUTPUT_FILE_DEFAULT" "${export_lines[@]}"
  elif is_sourced; then
    for line in "${export_lines[@]}"; do
      eval "$line"
    done
    echo "Exported variables into current shell."
  else
    local output_file
    output_file=$(ask "Write exports to file" "$OUTPUT_FILE_DEFAULT")
    write_exports_file "$output_file" "${export_lines[@]}"
    echo ""
    echo "========================================"
    echo "IMPORTANT: Variables are NOT yet active."
    echo "Run this to apply them to your shell:"
    echo ""
    echo "  source \"$output_file\""
    echo "========================================"
  fi

  echo ""
  echo "Configured values:"
  for line in "${export_lines[@]}"; do
    echo "  ${line#export }"
  done
}

main "$@"
