# This Dockerfile is used by OpenShift CI for running the Monitoring UI plugin tests
FROM cypress/browsers:22.15.0

# Install kubectl and oc
RUN wget -O oc.tar.gz https://mirror.openshift.com/pub/openshift-v4/x86_64/clients/ocp/latest/openshift-client-linux.tar.gz \
    && tar -xvzf oc.tar.gz \
    && chmod +x kubectl oc \
    && mv oc kubectl /usr/local/bin/ \
    && rm -rf oc.tar.gz

# Install apache2-utils for htpasswd required by OCP CI
RUN apt update && apt install -y apache2-utils \
    && rm -rf /var/lib/apt/lists/*