# OAuth configuration to use HTPasswd identity provider
#
# This configures OpenShift to authenticate users from the htpass-secret
# Apply htpasswd-secret.yaml first before applying this

apiVersion: config.openshift.io/v1
kind: OAuth
metadata:
  name: cluster
spec:
  identityProviders:
  - name: my_htpasswd_provider
    mappingMethod: claim
    type: HTPasswd
    htpasswd:
      fileData:
        name: htpass-secret
