kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: monitoring-plugin-cr
rules:
  - verbs:
      - "*"
    apiGroups:
      - monitoring.coreos.com
    resources:
      - alertmanagers
    resourceNames:
      - main
  - verbs:
      - "*"
    apiGroups:
      - monitoring.coreos.com
    resources:
      - alertmanagers/api
    resourceNames:
      - main
  - verbs:
      - "*"
    apiGroups:
      - monitoring.coreos.com
    resources:
      - prometheuses/api
    resourceNames:
      - k8s
  - verbs:
      - "*"
    apiGroups:
      - apiextensions.k8s.io
    resources:
      - customresourcedefinitions
  - verbs:
      - "*"
    apiGroups:
      - monitoring.coreos.com
    resources:
      - alertmanagers
