apiVersion: console.openshift.io/v1
kind: ConsolePlugin
metadata:
  name: {{ template "openshift-console-plugin.name" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "openshift-console-plugin.labels" . | nindent 4 }}
spec:
  backend:
    service:
      basePath: /
      name: {{ template "openshift-console-plugin.name" . }}
      namespace: {{ .Release.Namespace }}
      port: 9443
    type: Service
  displayName: {{ default (printf "%s" (include "openshift-console-plugin.name" .)) .Values.plugin.description }}
  i18n:
    loadType: ''
  proxy:
  - alias: backend
    authorization: UserToken
    endpoint:
      service:
        name: {{ template "openshift-console-plugin.name" . }}
        namespace: {{ .Release.Namespace }}
        port: 9443
      type: Service
  - alias: alertmanager-proxy
    authorization: UserToken
    endpoint:
      service:
        name: {{ template "openshift-console-plugin.name" . }}
        namespace: {{ .Release.Namespace }}
        port: 9444
      type: Service
  - alias: thanos-proxy
    authorization: UserToken
    endpoint:
      service:
        name: {{ template "openshift-console-plugin.name" . }}
        namespace: {{ .Release.Namespace }}
        port: 9445
      type: Service
