apiVersion: v1
kind: Service
metadata:
  {{- if not .Values.certificateSecretName }}
  annotations:
    service.alpha.openshift.io/serving-cert-secret-name: {{ template "openshift-console-plugin.certificateSecret" . }}
  {{- end }}
  {{- if and (.Values.plugin.acm.enabled) }}
  name: {{ .Values.plugin.acm.name }}
  {{- else }}
  name: {{ template "openshift-console-plugin.name" . }}
  {{- end }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "openshift-console-plugin.labels" . | nindent 4 }}
spec:
  ports:
    - name: {{ .Values.plugin.port }}-tcp
      protocol: TCP
      port: {{ .Values.plugin.port }}
      targetPort: {{ .Values.plugin.port }}
    {{- if and (.Values.plugin.acm.enabled) }}
    - name: alertmanager-proxy
      protocol: TCP
      port: {{ .Values.plugin.acm.alertmanager.pluginPort }}
      targetPort: {{ .Values.plugin.acm.alertmanager.pluginPort }}
    - name: thanos-proxy
      protocol: TCP
      port: {{ .Values.plugin.acm.thanos.pluginPort }}
      targetPort: {{ .Values.plugin.acm.thanos.pluginPort }}
    {{- end }}
  selector:
    {{- include "openshift-console-plugin.selectorLabels" . | nindent 4 }}
  type: ClusterIP
  sessionAffinity: None
