export const DataTestIDs = {
  AlertCluster: 'alert-cluster',
  AlertResourceIcon: 'alert-resource-icon',
  AlertResourceLink: 'alert-resource-link',
  AlertNamespace: 'alert-namespace',
  AlertState: 'alert-state',
  AlertSource: 'alert-source',
  AlertingRuleArrow: 'alerting-rule-arrow',
  AlertingRuleResourceIcon: 'alerting-rule-resource-icon',
  AlertingRuleResourceLink: 'alerting-rule-resource-link',
  AlertingRuleSeverityBadge: 'alerting-rule-severity-badge',
  AlertingRuleStateBadge: 'alerting-rule-state-badge',
  AlertingRuleTotalAlertsBadge: 'alerting-rule-total-alerts-badge',
  CancelButton: 'cancel-button',
  Breadcrumb: 'breadcrumb',
  DownloadCSVButton: 'download-csv-button',
  EmptyBoxBody: 'empty-box-body',
  ExpireSilenceButton: 'expire-silence-button',
  ExpireXSilencesButton: 'expire-x-silences-button',
  Expression: 'expression',
  KebabDropdownButton: 'kebab-dropdown-button',
  MetricGraphTimespanDropdown: 'graph-timespan-dropdown',
  MetricGraphTimespanInput: 'graph-timespan-input',
  MetricDisconnectedCheckbox: 'disconnected-checkbox',
  MetricDropdownPollInterval: 'dropdown-poll-interval',
  MetricGraphUnitsDropDown: 'graph-units-dropdown',
  MetricHideShowGraphButton: 'hide-show-graph-button',
  MetricResetZoomButton: 'reset-zoom-button',
  MetricStackedCheckbox: 'stacked-checkbox',
  MetricsPageActionsDropdownButton: 'actions-dropdown-button',
  MetricsPageAddQueryButton: 'add-query-button',
  MetricsPageAddQueryDropdownItem: 'add-query-dropdown-item',
  MetricsPageDeleteAllQueriesDropdownItem: 'delete-all-queries-dropdown-item',
  MetricsPageDeleteQueryDropdownItem: 'delete-query-dropdown-item',
  MetricsPageDisableEnableQuerySwitch: 'disable-enable-query-switch',
  MetricsPageDuplicateQueryDropdownItem: 'duplicate-query-dropdown-item',
  MetricsPageDisableEnableQueryDropdownItem: 'disable-enable-query-dropdown-item',
  MetricsPageExpandCollapseAllButton: 'expand-collapse-all-button',
  MetricsPageExpandCollapseAllDropdownItem: 'expand-collapse-all-dropdown-item',
  MetricsPageExportCsvDropdownItem: 'export-csv-dropdown-item',
  MetricsPageHideShowAllSeriesDropdownItem: 'hide-show-all-series-dropdown-item',
  MetricsPageInsertExampleQueryButton: 'insert-example-query-button',
  MetricsPageNoQueryEnteredTitle: 'no-query-entered-title',
  MetricsPageNoQueryEntered: 'no-query-entered',
  MetricsPageQueryTable: 'query-table',
  MetricsPageRunQueriesButton: 'run-queries-button',
  MetricsPageSelectAllUnselectAllDropdownItem: 'select-all-unselect-all-dropdown-item',
  MetricsPageSeriesButton: 'series-button',
  MetricsPageYellowNoDatapointsFound: 'yellow-no-datapoints-found',
  NameInput: 'name-filter-input',
  // TODO: remove this once we have a new dropdown component
  // NameLabelDropdown: 'dropdown-button',
  // NameLabelDropdownOptions: 'dropdown-menu',
  NameLabelDropdown: 'console-select-menu-toggle',
  NameLabelDropdownOptions: 'console-select-item',
  SeverityBadgeHeader: 'severity-badge-header',
  SeverityBadge: 'severity-badge',
  SilenceAlertDropdownItem: 'silence-alert-dropdown-item',
  SilenceButton: 'silence-button',
  SilenceEditDropdownItem: 'silence-edit-dropdown-item',
  SilenceExpireDropdownItem: 'silence-expire-dropdown-item',
  SilenceRecreateDropdownItem: 'silence-recreate-dropdown-item',
  SilenceResourceIcon: 'silence-resource-icon',
  SilenceResourceLink: 'silence-resource-link',
  SilencesPageFormTestIDs: {
    AddLabel: 'add-label',
    AlertLabelsDescription: 'alert-labels-description',
    Comment: 'comment',
    Creator: 'creator',
    Description: 'description-header',
    LabelName: 'label-name',
    LabelValue: 'label-value',
    NegativeMatcherCheckbox: 'negative-matcher-checkbox',
    Regex: 'regex-checkbox',
    RemoveLabel: 'remove-label',
    SilenceFrom: 'silence-from',
    SilenceFor: 'silence-for',
    SilenceForToggle: 'silence-for-toggle',
    SilenceUntil: 'silence-until',
    StartImmediately: 'start-immediately',
  },
  TypeaheadSelectInput: 'query-select-typeahead-input',
  Table: 'OUIA-Generated-Table',
};

export const LegacyDashboardPageTestIDs = {
  TimeRangeDropdown: 'time-range-dropdown',
  TimeRangeDropdownOptions: 'time-range-dropdown-options',
  PollIntervalDropdown: 'poll-interval-dropdown',
  PollIntervalDropdownOptions: 'poll-interval-dropdown-options',
  Inspect: 'inspect',
  ExportAsCsv: 'export-as-csv',
};

export const LegacyTestIDs = {
  ItemFilter: 'item-filter',
  SelectAllSilencesCheckbox: 'select-all-silences-checkbox',
};

export const Classes = {
  ExpandedRow: 'button[class="pf-v6-c-button pf-m-plain pf-m-expanded"]',
  ToExpandRow: 'button[class="pf-v6-c-button pf-m-plain"]',
  FilterDropdown: '.pf-v6-c-menu-toggle, .pf-v5-c-menu-toggle',
  FilterDropdownExpanded: '.pf-v6-c-menu-toggle.pf-m-expanded, .pf-v5-c-menu-toggle.pf-m-expanded',
  FilterDropdownOption: '.pf-v6-c-menu__item, .pf-c-select__menu-item',
  GraphCard: '.pf-v6-c-card.pf-m-compact',
  HorizontalNav: '.pf-v6-c-tabs__item, .co-m-horizontal-nav__menu-item',
  IndividualTag: '.pf-v6-c-label__text, .pf-v5-c-chip__text',
  LabelSuggestion: '.pf-v6-c-label__content.pf-m-clickable, .co-suggestion-line',
  LabelTag: '.pf-v6-c-label__text, .pf-v5-c-label__text',
  MainTag: '.pf-v6-c-label-group__label, .pf-v5-c-chip-group__label',
  MoreLessTag: '.pf-v6-c-label-group__label, .pf-v5-c-chip-group__label',
  SectionHeader: '.pf-v6-c-title.pf-m-h2, .co-section-heading',
  TableHeaderColumn: '.pf-v6-c-table__button, .pf-c-table__button',
  SilenceAlertTitle: '.pf-v6-c-alert__title, .pf-v5-c-alert__title',
  SilenceAlertDescription: '.pf-v6-c-alert__description, .pf-v5-c-alert__description',
  SilenceCommentWithoutError: '.pf-v6-c-form-control.pf-m-textarea.pf-m-resize-both',
  SilenceCommentWithError: '.pf-v6-c-form-control.pf-m-textarea.pf-m-resize-both.pf-m-error',
  SilenceCreatorWithError: '.pf-v6-c-form-control.pf-m-error',
  SilenceHelpText: '.pf-v6-c-helper-text__item-text, .pf-v5-c-helper-text__item-text',
  SilenceKebabDropdown: '.pf-v6-c-menu-toggle.pf-m-plain, .pf-v5-c-dropdown__toggle.pf-m-plain',
  SilenceLabelRow: '.pf-v6-l-grid.pf-m-all-12-col-on-sm.pf-m-all-4-col-on-md.pf-m-gutter, .row',
  SilenceState: '.pf-v6-l-stack__item, .co-break-word',
};
